#include "globalDefines.h"
!$Id: gibbs_rxn_table_m.f90,v 1.1.4.1 2006/04/04 01:28:57 rsankar Exp $
!Module to tabulate and lookup the change in Gibbs energy
!for each chemical reaction.
!This module was automatically generated by a perl script
!written by Ramanan Sankaran.
!
! BUG FIX Evatt Hawkes AUG-2005 - tabulation nondimensional slope was wrong
!
module gibbs_rxn_table_m
implicit none

private

integer, parameter:: NC_H2     =  1
integer, parameter:: NC_O2     =  2
integer, parameter:: NC_O      =  3
integer, parameter:: NC_OH     =  4
integer, parameter:: NC_H2O    =  5
integer, parameter:: NC_H      =  6
integer, parameter:: NC_HO2    =  7
integer, parameter:: NC_CO     =  8
integer, parameter:: NC_CO2    =  9
integer, parameter:: NC_HCO    = 10
integer, parameter:: NC_N2     = 11

integer, parameter:: npts=2001
real nd_inv_inc, nd_temp_lobound, nd_temp_hibound
! These variables tabulate the \delta_G/T for each reaction.
real, dimension(npts, 21):: Gibbs_table_aa, Gibbs_table_bb

!The coefficients for the polynomial fit of thermo properties
integer, parameter :: itrange = 2
real, dimension(7, itrange,  11) :: Coef
real, dimension(3,  11) :: CoefTbounds

public :: gibbs_lookup_all, gibbs_lookup, init_gibbstable

contains
!----------------------------------------------------------------------

!----------------------------------------------------------------------
subroutine init_gibbstable()
use reference_m, only: t_ref
implicit none

!----------------------------------------------------------------------
integer n
real inv_inc, temp_lobound, temp_hibound
real temp1, temp2, inc
real G1( 21), G2( 21)

!----------------------------------------------------------------------
temp_lobound = 250.0
temp_hibound = 3000.0
inc = ( temp_hibound - temp_lobound ) / real( npts-1 )
inv_inc = 1.0/inc

nd_temp_lobound = temp_lobound/t_ref
nd_temp_hibound = temp_hibound/t_ref
nd_inv_inc = inv_inc*t_ref

call init_coef

do n = 1, npts
  temp1 = temp_lobound + real(n-1)*inc
  temp2 = temp1 + inc
  call gibbs_rln(temp1, G1)
  call gibbs_rln(temp2, G2)
  Gibbs_table_aa(n, :) = (G2(:)-G1(:))*inv_inc
  Gibbs_table_bb(n, :) = G1(:)-Gibbs_table_aa(n, :)*temp1
  Gibbs_table_aa(n, :) = Gibbs_table_aa(n,:)*t_ref
end do
end subroutine init_gibbstable

!----------------------------------------------------------------------
subroutine init_coef()
implicit none

CoefTbounds(1, NC_H2) =   0300.00 
CoefTbounds(2, NC_H2) =  1000.00
CoefTbounds(3, NC_H2) =   5000.00 

Coef(1, 1, NC_H2) =  0.03298124E+02
Coef(2, 1, NC_H2) =  0.08249442E-02
Coef(3, 1, NC_H2) = -0.08143015E-05
Coef(4, 1, NC_H2) = -0.09475434E-09
Coef(5, 1, NC_H2) =  0.04134872E-11
Coef(6, 1, NC_H2) = -0.01012521E+05
Coef(7, 1, NC_H2) = -0.03294094E+02

Coef(1, 2, NC_H2) =  0.02991423E+02
Coef(2, 2, NC_H2) =  0.07000644E-02
Coef(3, 2, NC_H2) = -0.05633829E-06
Coef(4, 2, NC_H2) = -0.09231578E-10
Coef(5, 2, NC_H2) =  0.01582752E-13
Coef(6, 2, NC_H2) = -0.08350340E+04
Coef(7, 2, NC_H2) = -0.01355110E+02

CoefTbounds(1, NC_O2) =   0300.00 
CoefTbounds(2, NC_O2) =  1000.00
CoefTbounds(3, NC_O2) =   5000.00 

Coef(1, 1, NC_O2) =  0.03212936E+02
Coef(2, 1, NC_O2) =  0.01127486E-01
Coef(3, 1, NC_O2) = -0.05756150E-05
Coef(4, 1, NC_O2) =  0.01313877E-07
Coef(5, 1, NC_O2) = -0.08768554E-11
Coef(6, 1, NC_O2) = -0.01005249E+05
Coef(7, 1, NC_O2) =  0.06034738E+02

Coef(1, 2, NC_O2) =  0.03697578E+02
Coef(2, 2, NC_O2) =  0.06135197E-02
Coef(3, 2, NC_O2) = -0.01258842E-05
Coef(4, 2, NC_O2) =  0.01775281E-09
Coef(5, 2, NC_O2) = -0.01136435E-13
Coef(6, 2, NC_O2) = -0.01233930E+05
Coef(7, 2, NC_O2) =  0.03189166E+02

CoefTbounds(1, NC_O) =   0300.00 
CoefTbounds(2, NC_O) =  1000.00
CoefTbounds(3, NC_O) =   5000.00 

Coef(1, 1, NC_O) =  0.02946429E+02
Coef(2, 1, NC_O) = -0.01638166E-01
Coef(3, 1, NC_O) =  0.02421032E-04
Coef(4, 1, NC_O) = -0.01602843E-07
Coef(5, 1, NC_O) =  0.03890696E-11
Coef(6, 1, NC_O) =  0.02914764E+06
Coef(7, 1, NC_O) =  0.02963995E+02

Coef(1, 2, NC_O) =  0.02542060E+02
Coef(2, 2, NC_O) = -0.02755062E-03
Coef(3, 2, NC_O) = -0.03102803E-07
Coef(4, 2, NC_O) =  0.04551067E-10
Coef(5, 2, NC_O) = -0.04368052E-14
Coef(6, 2, NC_O) =  0.02923080E+06
Coef(7, 2, NC_O) =  0.04920308E+02

CoefTbounds(1, NC_OH) =    200.000
CoefTbounds(2, NC_OH) =  1000.  
CoefTbounds(3, NC_OH) =   6000.000

Coef(1, 1, NC_OH) =  4.12530561E+00
Coef(2, 1, NC_OH) = -3.22544939E-03
Coef(3, 1, NC_OH) =  6.52764691E-06
Coef(4, 1, NC_OH) = -5.79853643E-09
Coef(5, 1, NC_OH) =  2.06237379E-12
Coef(6, 1, NC_OH) =  3.34630913E+03
Coef(7, 1, NC_OH) = -6.90432960E-01

Coef(1, 2, NC_OH) =  2.86472886E+00
Coef(2, 2, NC_OH) =  1.05650448E-03
Coef(3, 2, NC_OH) = -2.59082758E-07
Coef(4, 2, NC_OH) =  3.05218674E-11
Coef(5, 2, NC_OH) = -1.33195876E-15
Coef(6, 2, NC_OH) =  3.68362875E+03
Coef(7, 2, NC_OH) =  5.70164073E+00

CoefTbounds(1, NC_H2O) =   0300.00 
CoefTbounds(2, NC_H2O) =  1000.00
CoefTbounds(3, NC_H2O) =   5000.00 

Coef(1, 1, NC_H2O) =  0.03386842E+02
Coef(2, 1, NC_H2O) =  0.03474982E-01
Coef(3, 1, NC_H2O) = -0.06354696E-04
Coef(4, 1, NC_H2O) =  0.06968581E-07
Coef(5, 1, NC_H2O) = -0.02506588E-10
Coef(6, 1, NC_H2O) = -0.03020811E+06
Coef(7, 1, NC_H2O) =  0.02590233E+02

Coef(1, 2, NC_H2O) =  0.02672146E+02
Coef(2, 2, NC_H2O) =  0.03056293E-01
Coef(3, 2, NC_H2O) = -0.08730260E-05
Coef(4, 2, NC_H2O) =  0.01200996E-08
Coef(5, 2, NC_H2O) = -0.06391618E-13
Coef(6, 2, NC_H2O) = -0.02989921E+06
Coef(7, 2, NC_H2O) =  0.06862817E+02

CoefTbounds(1, NC_H) =   0300.00 
CoefTbounds(2, NC_H) =  1000.00
CoefTbounds(3, NC_H) =   5000.00 

Coef(1, 1, NC_H) =  0.02500000E+02
Coef(2, 1, NC_H) =  0.00000000E+00
Coef(3, 1, NC_H) =  0.00000000E+00
Coef(4, 1, NC_H) =  0.00000000E+00
Coef(5, 1, NC_H) =  0.00000000E+00
Coef(6, 1, NC_H) =  0.02547163E+06
Coef(7, 1, NC_H) = -0.04601176E+01

Coef(1, 2, NC_H) =  0.02500000E+02
Coef(2, 2, NC_H) =  0.00000000E+00
Coef(3, 2, NC_H) =  0.00000000E+00
Coef(4, 2, NC_H) =  0.00000000E+00
Coef(5, 2, NC_H) =  0.00000000E+00
Coef(6, 2, NC_H) =  0.02547163E+06
Coef(7, 2, NC_H) = -0.04601176E+01

CoefTbounds(1, NC_HO2) =    200.000
CoefTbounds(2, NC_HO2) =   1000.0
CoefTbounds(3, NC_HO2) =   3500.000

Coef(1, 1, NC_HO2) =  4.30179801E+00
Coef(2, 1, NC_HO2) = -4.74912051E-03
Coef(3, 1, NC_HO2) =  2.11582891E-05
Coef(4, 1, NC_HO2) = -2.42763894E-08
Coef(5, 1, NC_HO2) =  9.29225124E-12
Coef(6, 1, NC_HO2) =  2.94808040E+02
Coef(7, 1, NC_HO2) =  3.71666245E+00

Coef(1, 2, NC_HO2) =  4.01721090E+00
Coef(2, 2, NC_HO2) =  2.23982013E-03
Coef(3, 2, NC_HO2) = -6.33658150E-07
Coef(4, 2, NC_HO2) =  1.14246370E-10
Coef(5, 2, NC_HO2) = -1.07908535E-14
Coef(6, 2, NC_HO2) =  1.11856713E+02
Coef(7, 2, NC_HO2) =  3.78510215E+00

CoefTbounds(1, NC_CO) =   0300.00 
CoefTbounds(2, NC_CO) =  1000.00
CoefTbounds(3, NC_CO) =   5000.00 

Coef(1, 1, NC_CO) =  0.03262452E+02
Coef(2, 1, NC_CO) =  0.01511941E-01
Coef(3, 1, NC_CO) = -0.03881755E-04
Coef(4, 1, NC_CO) =  0.05581944E-07
Coef(5, 1, NC_CO) = -0.02474951E-10
Coef(6, 1, NC_CO) = -0.01431054E+06
Coef(7, 1, NC_CO) =  0.04848897E+02

Coef(1, 2, NC_CO) =  0.03025078E+02
Coef(2, 2, NC_CO) =  0.01442689E-01
Coef(3, 2, NC_CO) = -0.05630828E-05
Coef(4, 2, NC_CO) =  0.01018581E-08
Coef(5, 2, NC_CO) = -0.06910952E-13
Coef(6, 2, NC_CO) = -0.01426835E+06
Coef(7, 2, NC_CO) =  0.06108218E+02

CoefTbounds(1, NC_CO2) =   0300.00 
CoefTbounds(2, NC_CO2) =  1000.00
CoefTbounds(3, NC_CO2) =   5000.00 

Coef(1, 1, NC_CO2) =  0.02275725E+02
Coef(2, 1, NC_CO2) =  0.09922072E-01
Coef(3, 1, NC_CO2) = -0.01040911E-03
Coef(4, 1, NC_CO2) =  0.06866687E-07
Coef(5, 1, NC_CO2) = -0.02117280E-10
Coef(6, 1, NC_CO2) = -0.04837314E+06
Coef(7, 1, NC_CO2) =  0.01018849E+03

Coef(1, 2, NC_CO2) =  0.04453623E+02
Coef(2, 2, NC_CO2) =  0.03140169E-01
Coef(3, 2, NC_CO2) = -0.01278411E-04
Coef(4, 2, NC_CO2) =  0.02393997E-08
Coef(5, 2, NC_CO2) = -0.01669033E-12
Coef(6, 2, NC_CO2) = -0.04896696E+06
Coef(7, 2, NC_CO2) = -0.09553959E+01

CoefTbounds(1, NC_HCO) =   0300.00 
CoefTbounds(2, NC_HCO) =  1000.00
CoefTbounds(3, NC_HCO) =   5000.00 

Coef(1, 1, NC_HCO) =  0.02898330E+02
Coef(2, 1, NC_HCO) =  0.06199147E-01
Coef(3, 1, NC_HCO) = -0.09623084E-04
Coef(4, 1, NC_HCO) =  0.01089825E-06
Coef(5, 1, NC_HCO) = -0.04574885E-10
Coef(6, 1, NC_HCO) =  0.04159922E+05
Coef(7, 1, NC_HCO) =  0.08983614E+02

Coef(1, 2, NC_HCO) =  0.03557271E+02
Coef(2, 2, NC_HCO) =  0.03345573E-01
Coef(3, 2, NC_HCO) = -0.01335006E-04
Coef(4, 2, NC_HCO) =  0.02470573E-08
Coef(5, 2, NC_HCO) = -0.01713851E-12
Coef(6, 2, NC_HCO) =  0.03916324E+05
Coef(7, 2, NC_HCO) =  0.05552299E+02

CoefTbounds(1, NC_N2) =   0300.00 
CoefTbounds(2, NC_N2) =  1000.00
CoefTbounds(3, NC_N2) =   5000.00 

Coef(1, 1, NC_N2) =  0.03298677E+02
Coef(2, 1, NC_N2) =  0.01408240E-01
Coef(3, 1, NC_N2) = -0.03963222E-04
Coef(4, 1, NC_N2) =  0.05641515E-07
Coef(5, 1, NC_N2) = -0.02444855E-10
Coef(6, 1, NC_N2) = -0.01020900E+05
Coef(7, 1, NC_N2) =  0.03950372E+02

Coef(1, 2, NC_N2) =  0.02926640E+02
Coef(2, 2, NC_N2) =  0.01487977E-01
Coef(3, 2, NC_N2) = -0.05684761E-05
Coef(4, 2, NC_N2) =  0.01009704E-08
Coef(5, 2, NC_N2) = -0.06753351E-13
Coef(6, 2, NC_N2) = -0.09227977E+04
Coef(7, 2, NC_N2) =  0.05980528E+02

end subroutine init_coef

!----------------------------------------------------------------------
!Computes G/R = H/R-T*S/R for all species
subroutine my_ckgml(T, G)
implicit none

real, intent(in)  :: T
real, intent(out) :: G( 11)
integer m

do m = 1,  11
  G(m) = hml_spcs(m,T) - T*sml_spcs(m, T)
end do

return
end subroutine my_ckgml

!----------------------------------------------------------------------
!Returns H/R for a single species
real function hml_spcs(m, temp)
implicit none
integer, intent(in) :: m
real, intent(in) :: temp
integer :: nt

if (temp < coefTbounds(2,m)) then
  nt = 1
else
  nt = 2
end if

hml_spcs =      coef(6,nt,m)                     &
     + temp * ( coef(1,nt,m)                     &
     + temp * ( coef(2,nt,m) / 2.0               &
     + temp * ( coef(3,nt,m) / 3.0               &
     + temp * ( coef(4,nt,m) / 4.0               &
     + temp *   coef(5,nt,m) / 5.0 ))))

return
end function hml_spcs

!----------------------------------------------------------------------
!Returns S/R for a single species
real function sml_spcs(m, temp)
implicit none
integer, intent(in) :: m
real, intent(in) :: temp
integer :: nt

if (temp < coefTbounds(2,m)) then
  nt = 1
else
  nt = 2
end if

sml_spcs =      coef(1,nt,m)*log(temp)           &
     +          coef(7,nt,m)                     &
     + temp * ( coef(2,nt,m)                     &
     + temp * ( coef(3,nt,m) / 2.0               &
     + temp * ( coef(4,nt,m) / 3.0               &
     + temp *   coef(5,nt,m) / 4.0 )))

return
end function sml_spcs

!----------------------------------------------------------------------
subroutine gibbs_rln (T, G)

implicit none

real, intent(in) :: T
real, intent(out) :: G( 21)
real cgspl( 11)

call my_ckgml(T, cgspl)

!----------------------------------------------------------------------
!----------------------------------------------------------------------
! 1. H+O2= O+OH                 
G(1) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_O)-1.0*cgspl(NC_O2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 2. O+H2= H+OH                 
G(2) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_O)-1.0*cgspl(NC_H2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 3. H2+OH= H2O+H               
G(3) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_H2)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 4. O+H2O= OH+OH               
G(4) = -1.0*cgspl(NC_O)-1.0*cgspl(NC_H2O)+2.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 5. H2+M= H+H+M                
G(5) = +2.0*cgspl(NC_H)-1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 6. O+O+M= O2+M                
G(6) = -2.0*cgspl(NC_O)+1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 7. O+H+M= OH+M                
G(7) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_O)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 8. H+OH+M= H2O+M               
G(8) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 9. H+O2+M= HO2+M      
G(9) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 10. HO2+H= H2+O2               
G(10) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_HO2)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 11. HO2+H= OH+OH               
G(11) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_HO2)+2.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 12. HO2+O= O2+OH               
G(12) = -1.0*cgspl(NC_O)-1.0*cgspl(NC_HO2)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 13. HO2+OH= H2O+O2             
G(13) = -1.0*cgspl(NC_HO2)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 14. CO+O+M= CO2+M           
G(14) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)

!----------------------------------------------------------------------
! 15. CO+O2= CO2+O               
G(15) = +1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 16. CO+HO2= CO2+OH             
G(16) = -1.0*cgspl(NC_HO2)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 17. CO+OH= CO2+H                    
G(17) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 18. HCO+M= H+CO+M           
G(18) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 19. HCO+O2= CO+HO2             
G(19) = +1.0*cgspl(NC_HO2)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 20. HCO+H= CO+H2               
G(20) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)+1.0*cgspl(NC_H2)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 21. HCO + O =  CO2 + H                 
G(21) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_HCO)

G(:) = G(:)/T
return
end subroutine gibbs_rln

!----------------------------------------------------------------------
!Returns the change in gibbs energy for a given reaction number
!at all points in the domain.
!Note that T is in non-dimensional units.
subroutine gibbs_lookup_all(T, r, G)
use param_m, only: nx, ny, nz
implicit none
real, dimension(nx, ny, nz), intent(in) :: T
integer, intent(in) :: r
real, dimension(nx, ny, nz), intent(out) :: G

integer i, j, k, n

do k = 1, nz
  do j = 1, ny
    do i = 1, nx
      n = int( (T(i,j,k)-nd_temp_lobound)*nd_inv_inc ) + 1
      G(i,j,k) = Gibbs_table_aa(n,r)*T(i,j,k) + Gibbs_table_bb(n,r)
    end do
  end do
end do

end subroutine gibbs_lookup_all
!----------------------------------------------------------------------

!----------------------------------------------------------------------
!Returns the change in gibbs energy for a given reaction number
!Note that T is in non-dimensional units.
subroutine gibbs_lookup(T, r, G)
implicit none
real, intent(in) :: T
integer, intent(in) :: r
real, intent(out) :: G

integer n

n = int( (T-nd_temp_lobound)*nd_inv_inc ) + 1
G = Gibbs_table_aa(n,r)*T + Gibbs_table_bb(n,r)

end subroutine gibbs_lookup
!----------------------------------------------------------------------
end module gibbs_rxn_table_m
