#include "globalDefines.h"
!Module to tabulate and lookup the change in Gibbs energy
!for each chemical reaction.
!This module was automatically generated by a perl script
!written by Ramanan Sankaran.
module gibbs_rxn_table_m
implicit none

private

integer, parameter:: NC_H2     =  1
integer, parameter:: NC_H      =  2
integer, parameter:: NC_O      =  3
integer, parameter:: NC_O2     =  4
integer, parameter:: NC_OH     =  5
integer, parameter:: NC_H2O    =  6
integer, parameter:: NC_HO2    =  7
integer, parameter:: NC_CH3    =  8
integer, parameter:: NC_CH4    =  9
integer, parameter:: NC_CO     = 10
integer, parameter:: NC_CO2    = 11
integer, parameter:: NC_CH2O   = 12
integer, parameter:: NC_N2     = 13
integer, parameter:: NC_CH2    = 14
integer, parameter:: NC_CH2S   = 15
integer, parameter:: NC_HCO    = 16
integer, parameter:: NC_CH2OH  = 17

integer, parameter:: npts=2001
real nd_inv_inc, nd_temp_lobound, nd_temp_hibound
! These variables tabulate the \delta_G/T for each reaction.
real, dimension(npts, 73):: Gibbs_table_aa, Gibbs_table_bb

!The coefficients for the polynomial fit of thermo properties
integer, parameter :: itrange = 2
real, dimension(7, itrange,  17) :: Coef
real, dimension(3,  17) :: CoefTbounds

integer, dimension(:,:,:), allocatable :: index

public :: gibbs_lookup_all, gibbs_lookup, init_gibbstable
public :: gibbs_compute_index

contains
!----------------------------------------------------------------------

!----------------------------------------------------------------------
subroutine init_gibbstable()
use reference_m, only: t_ref
use param_m, only: nx, ny, nz
implicit none

!----------------------------------------------------------------------
integer n
real inv_inc, temp_lobound, temp_hibound
real temp1, temp2, inc
real G1( 73), G2( 73)

!----------------------------------------------------------------------
temp_lobound = 250.0
temp_hibound = 3000.0
inc = ( temp_hibound - temp_lobound ) / real( npts-1 )
inv_inc = 1.0/inc

nd_temp_lobound = temp_lobound/t_ref
nd_temp_hibound = temp_hibound/t_ref
nd_inv_inc = inv_inc*t_ref

call init_coef

do n = 1, npts
  temp1 = temp_lobound + real(n-1)*inc
  temp2 = temp1 + inc
  call gibbs_rln(temp1, G1)
  call gibbs_rln(temp2, G2)
  Gibbs_table_aa(n, :) = (G2(:)-G1(:))*inv_inc
  Gibbs_table_bb(n, :) = G1(:)-Gibbs_table_aa(n, :)*temp1
  Gibbs_table_aa(n, :) = Gibbs_table_aa(n,  :)  * t_ref
end do

allocate(index(nx, ny, nz))
end subroutine init_gibbstable

!----------------------------------------------------------------------
subroutine init_coef()
implicit none

CoefTbounds(1, NC_H2) =    200.000
CoefTbounds(2, NC_H2) =    1000.
CoefTbounds(3, NC_H2) =   3500.000

Coef(1, 1, NC_H2) =  2.34433112E+00
Coef(2, 1, NC_H2) =  7.98052075E-03
Coef(3, 1, NC_H2) = -1.94781510E-05
Coef(4, 1, NC_H2) =  2.01572094E-08
Coef(5, 1, NC_H2) = -7.37611761E-12
Coef(6, 1, NC_H2) = -9.17935173E+02
Coef(7, 1, NC_H2) =  6.83010238E-01

Coef(1, 2, NC_H2) =  3.33727920E+00
Coef(2, 2, NC_H2) = -4.94024731E-05
Coef(3, 2, NC_H2) =  4.99456778E-07
Coef(4, 2, NC_H2) = -1.79566394E-10
Coef(5, 2, NC_H2) =  2.00255376E-14
Coef(6, 2, NC_H2) = -9.50158922E+02
Coef(7, 2, NC_H2) = -3.20502331E+00

CoefTbounds(1, NC_H) =    200.000
CoefTbounds(2, NC_H) =    1000.
CoefTbounds(3, NC_H) =   3500.000

Coef(1, 1, NC_H) =  2.50000000E+00
Coef(2, 1, NC_H) =  7.05332819E-13
Coef(3, 1, NC_H) = -1.99591964E-15
Coef(4, 1, NC_H) =  2.30081632E-18
Coef(5, 1, NC_H) = -9.27732332E-22
Coef(6, 1, NC_H) =  2.54736599E+04
Coef(7, 1, NC_H) = -4.46682853E-01

Coef(1, 2, NC_H) =  2.50000001E+00
Coef(2, 2, NC_H) = -2.30842973E-11
Coef(3, 2, NC_H) =  1.61561948E-14
Coef(4, 2, NC_H) = -4.73515235E-18
Coef(5, 2, NC_H) =  4.98197357E-22
Coef(6, 2, NC_H) =  2.54736599E+04
Coef(7, 2, NC_H) = -4.46682914E-01

CoefTbounds(1, NC_O) =    200.000
CoefTbounds(2, NC_O) =   1000.0
CoefTbounds(3, NC_O) =   3500.000

Coef(1, 1, NC_O) =  3.16826710E+00
Coef(2, 1, NC_O) = -3.27931884E-03
Coef(3, 1, NC_O) =  6.64306396E-06
Coef(4, 1, NC_O) = -6.12806624E-09
Coef(5, 1, NC_O) =  2.11265971E-12
Coef(6, 1, NC_O) =  2.91222592E+04
Coef(7, 1, NC_O) =  2.05193346E+00

Coef(1, 2, NC_O) =  2.56942078E+00
Coef(2, 2, NC_O) = -8.59741137E-05
Coef(3, 2, NC_O) =  4.19484589E-08
Coef(4, 2, NC_O) = -1.00177799E-11
Coef(5, 2, NC_O) =  1.22833691E-15
Coef(6, 2, NC_O) =  2.92175791E+04
Coef(7, 2, NC_O) =  4.78433864E+00

CoefTbounds(1, NC_O2) =    200.000
CoefTbounds(2, NC_O2) =   1000.0
CoefTbounds(3, NC_O2) =   3500.000

Coef(1, 1, NC_O2) =  3.78245636E+00
Coef(2, 1, NC_O2) = -2.99673416E-03
Coef(3, 1, NC_O2) =  9.84730201E-06
Coef(4, 1, NC_O2) = -9.68129509E-09
Coef(5, 1, NC_O2) =  3.24372837E-12
Coef(6, 1, NC_O2) = -1.06394356E+03
Coef(7, 1, NC_O2) =  3.65767573E+00

Coef(1, 2, NC_O2) =  3.28253784E+00
Coef(2, 2, NC_O2) =  1.48308754E-03
Coef(3, 2, NC_O2) = -7.57966669E-07
Coef(4, 2, NC_O2) =  2.09470555E-10
Coef(5, 2, NC_O2) = -2.16717794E-14
Coef(6, 2, NC_O2) = -1.08845772E+03
Coef(7, 2, NC_O2) =  5.45323129E+00

CoefTbounds(1, NC_OH) =    200.000
CoefTbounds(2, NC_OH) =   1000.0
CoefTbounds(3, NC_OH) =   3500.000

Coef(1, 1, NC_OH) =  3.99201543E+00
Coef(2, 1, NC_OH) = -2.40131752E-03
Coef(3, 1, NC_OH) =  4.61793841E-06
Coef(4, 1, NC_OH) = -3.88113333E-09
Coef(5, 1, NC_OH) =  1.36411470E-12
Coef(6, 1, NC_OH) =  3.61508056E+03
Coef(7, 1, NC_OH) = -1.03925458E-01

Coef(1, 2, NC_OH) =  3.09288767E+00
Coef(2, 2, NC_OH) =  5.48429716E-04
Coef(3, 2, NC_OH) =  1.26505228E-07
Coef(4, 2, NC_OH) = -8.79461556E-11
Coef(5, 2, NC_OH) =  1.17412376E-14
Coef(6, 2, NC_OH) =  3.85865700E+03
Coef(7, 2, NC_OH) =  4.47669610E+00

CoefTbounds(1, NC_H2O) =    200.000
CoefTbounds(2, NC_H2O) =   1000.0
CoefTbounds(3, NC_H2O) =   3500.000

Coef(1, 1, NC_H2O) =  4.19864056E+00
Coef(2, 1, NC_H2O) = -2.03643410E-03
Coef(3, 1, NC_H2O) =  6.52040211E-06
Coef(4, 1, NC_H2O) = -5.48797062E-09
Coef(5, 1, NC_H2O) =  1.77197817E-12
Coef(6, 1, NC_H2O) = -3.02937267E+04
Coef(7, 1, NC_H2O) = -8.49032208E-01

Coef(1, 2, NC_H2O) =  3.03399249E+00
Coef(2, 2, NC_H2O) =  2.17691804E-03
Coef(3, 2, NC_H2O) = -1.64072518E-07
Coef(4, 2, NC_H2O) = -9.70419870E-11
Coef(5, 2, NC_H2O) =  1.68200992E-14
Coef(6, 2, NC_H2O) = -3.00042971E+04
Coef(7, 2, NC_H2O) =  4.96677010E+00

CoefTbounds(1, NC_HO2) =    200.000
CoefTbounds(2, NC_HO2) =   1000.0
CoefTbounds(3, NC_HO2) =   3500.000

Coef(1, 1, NC_HO2) =  4.30179801E+00
Coef(2, 1, NC_HO2) = -4.74912051E-03
Coef(3, 1, NC_HO2) =  2.11582891E-05
Coef(4, 1, NC_HO2) = -2.42763894E-08
Coef(5, 1, NC_HO2) =  9.29225124E-12
Coef(6, 1, NC_HO2) =  2.94808040E+02
Coef(7, 1, NC_HO2) =  3.71666245E+00

Coef(1, 2, NC_HO2) =  4.01721090E+00
Coef(2, 2, NC_HO2) =  2.23982013E-03
Coef(3, 2, NC_HO2) = -6.33658150E-07
Coef(4, 2, NC_HO2) =  1.14246370E-10
Coef(5, 2, NC_HO2) = -1.07908535E-14
Coef(6, 2, NC_HO2) =  1.11856713E+02
Coef(7, 2, NC_HO2) =  3.78510215E+00

CoefTbounds(1, NC_CH3) =    200.000
CoefTbounds(2, NC_CH3) =   1000.0
CoefTbounds(3, NC_CH3) =   3500.000

Coef(1, 1, NC_CH3) =  3.67359040E+00
Coef(2, 1, NC_CH3) =  2.01095175E-03
Coef(3, 1, NC_CH3) =  5.73021856E-06
Coef(4, 1, NC_CH3) = -6.87117425E-09
Coef(5, 1, NC_CH3) =  2.54385734E-12
Coef(6, 1, NC_CH3) =  1.64449988E+04
Coef(7, 1, NC_CH3) =  1.60456433E+00

Coef(1, 2, NC_CH3) =  2.28571772E+00
Coef(2, 2, NC_CH3) =  7.23990037E-03
Coef(3, 2, NC_CH3) = -2.98714348E-06
Coef(4, 2, NC_CH3) =  5.95684644E-10
Coef(5, 2, NC_CH3) = -4.67154394E-14
Coef(6, 2, NC_CH3) =  1.67755843E+04
Coef(7, 2, NC_CH3) =  8.48007179E+00

CoefTbounds(1, NC_CH4) =    200.000
CoefTbounds(2, NC_CH4) =   1000.0
CoefTbounds(3, NC_CH4) =   3500.000

Coef(1, 1, NC_CH4) =  5.14987613E+00
Coef(2, 1, NC_CH4) = -1.36709788E-02
Coef(3, 1, NC_CH4) =  4.91800599E-05
Coef(4, 1, NC_CH4) = -4.84743026E-08
Coef(5, 1, NC_CH4) =  1.66693956E-11
Coef(6, 1, NC_CH4) = -1.02466476E+04
Coef(7, 1, NC_CH4) = -4.64130376E+00

Coef(1, 2, NC_CH4) =  7.48514950E-02
Coef(2, 2, NC_CH4) =  1.33909467E-02
Coef(3, 2, NC_CH4) = -5.73285809E-06
Coef(4, 2, NC_CH4) =  1.22292535E-09
Coef(5, 2, NC_CH4) = -1.01815230E-13
Coef(6, 2, NC_CH4) = -9.46834459E+03
Coef(7, 2, NC_CH4) =  1.84373180E+01

CoefTbounds(1, NC_CO) =    200.000
CoefTbounds(2, NC_CO) =   1000.0
CoefTbounds(3, NC_CO) =   3500.000

Coef(1, 1, NC_CO) =  3.57953347E+00
Coef(2, 1, NC_CO) = -6.10353680E-04
Coef(3, 1, NC_CO) =  1.01681433E-06
Coef(4, 1, NC_CO) =  9.07005884E-10
Coef(5, 1, NC_CO) = -9.04424499E-13
Coef(6, 1, NC_CO) = -1.43440860E+04
Coef(7, 1, NC_CO) =  3.50840928E+00

Coef(1, 2, NC_CO) =  2.71518561E+00
Coef(2, 2, NC_CO) =  2.06252743E-03
Coef(3, 2, NC_CO) = -9.98825771E-07
Coef(4, 2, NC_CO) =  2.30053008E-10
Coef(5, 2, NC_CO) = -2.03647716E-14
Coef(6, 2, NC_CO) = -1.41518724E+04
Coef(7, 2, NC_CO) =  7.81868772E+00

CoefTbounds(1, NC_CO2) =    200.000
CoefTbounds(2, NC_CO2) =   1000.0
CoefTbounds(3, NC_CO2) =   3500.000

Coef(1, 1, NC_CO2) =  2.35677352E+00
Coef(2, 1, NC_CO2) =  8.98459677E-03
Coef(3, 1, NC_CO2) = -7.12356269E-06
Coef(4, 1, NC_CO2) =  2.45919022E-09
Coef(5, 1, NC_CO2) = -1.43699548E-13
Coef(6, 1, NC_CO2) = -4.83719697E+04
Coef(7, 1, NC_CO2) =  9.90105222E+00

Coef(1, 2, NC_CO2) =  3.85746029E+00
Coef(2, 2, NC_CO2) =  4.41437026E-03
Coef(3, 2, NC_CO2) = -2.21481404E-06
Coef(4, 2, NC_CO2) =  5.23490188E-10
Coef(5, 2, NC_CO2) = -4.72084164E-14
Coef(6, 2, NC_CO2) = -4.87591660E+04
Coef(7, 2, NC_CO2) =  2.27163806E+00

CoefTbounds(1, NC_CH2O) =    200.000
CoefTbounds(2, NC_CH2O) =   1000.0
CoefTbounds(3, NC_CH2O) =   3500.000

Coef(1, 1, NC_CH2O) =  4.79372315E+00
Coef(2, 1, NC_CH2O) = -9.90833369E-03
Coef(3, 1, NC_CH2O) =  3.73220008E-05
Coef(4, 1, NC_CH2O) = -3.79285261E-08
Coef(5, 1, NC_CH2O) =  1.31772652E-11
Coef(6, 1, NC_CH2O) = -1.43089567E+04
Coef(7, 1, NC_CH2O) =  6.02812900E-01

Coef(1, 2, NC_CH2O) =  1.76069008E+00
Coef(2, 2, NC_CH2O) =  9.20000082E-03
Coef(3, 2, NC_CH2O) = -4.42258813E-06
Coef(4, 2, NC_CH2O) =  1.00641212E-09
Coef(5, 2, NC_CH2O) = -8.83855640E-14
Coef(6, 2, NC_CH2O) = -1.39958323E+04
Coef(7, 2, NC_CH2O) =  1.36563230E+01

CoefTbounds(1, NC_N2) =   0300.00 
CoefTbounds(2, NC_N2) =  1000.00
CoefTbounds(3, NC_N2) =   5000.00 

Coef(1, 1, NC_N2) =  0.03298677E+02
Coef(2, 1, NC_N2) =  0.14082404E-02
Coef(3, 1, NC_N2) = -0.03963222E-04
Coef(4, 1, NC_N2) =  0.05641515E-07
Coef(5, 1, NC_N2) = -0.02444854E-10
Coef(6, 1, NC_N2) = -0.10208999E+04
Coef(7, 1, NC_N2) =  0.03950372E+02

Coef(1, 2, NC_N2) =  0.02926640E+02
Coef(2, 2, NC_N2) =  0.14879768E-02
Coef(3, 2, NC_N2) = -0.05684760E-05
Coef(4, 2, NC_N2) =  0.10097038E-09
Coef(5, 2, NC_N2) = -0.06753351E-13
Coef(6, 2, NC_N2) = -0.09227977E+04
Coef(7, 2, NC_N2) =  0.05980528E+02

CoefTbounds(1, NC_CH2) =    200.000
CoefTbounds(2, NC_CH2) =   1000.0
CoefTbounds(3, NC_CH2) =   3500.000

Coef(1, 1, NC_CH2) =  3.76267867E+00
Coef(2, 1, NC_CH2) =  9.68872143E-04
Coef(3, 1, NC_CH2) =  2.79489841E-06
Coef(4, 1, NC_CH2) = -3.85091153E-09
Coef(5, 1, NC_CH2) =  1.68741719E-12
Coef(6, 1, NC_CH2) =  4.60040401E+04
Coef(7, 1, NC_CH2) =  1.56253185E+00

Coef(1, 2, NC_CH2) =  2.87410113E+00
Coef(2, 2, NC_CH2) =  3.65639292E-03
Coef(3, 2, NC_CH2) = -1.40894597E-06
Coef(4, 2, NC_CH2) =  2.60179549E-10
Coef(5, 2, NC_CH2) = -1.87727567E-14
Coef(6, 2, NC_CH2) =  4.62636040E+04
Coef(7, 2, NC_CH2) =  6.17119324E+00

CoefTbounds(1, NC_CH2S) =    200.000
CoefTbounds(2, NC_CH2S) =   1000.0
CoefTbounds(3, NC_CH2S) =   3500.000

Coef(1, 1, NC_CH2S) =  4.19860411E+00
Coef(2, 1, NC_CH2S) = -2.36661419E-03
Coef(3, 1, NC_CH2S) =  8.23296220E-06
Coef(4, 1, NC_CH2S) = -6.68815981E-09
Coef(5, 1, NC_CH2S) =  1.94314737E-12
Coef(6, 1, NC_CH2S) =  5.04968163E+04
Coef(7, 1, NC_CH2S) = -7.69118967E-01

Coef(1, 2, NC_CH2S) =  2.29203842E+00
Coef(2, 2, NC_CH2S) =  4.65588637E-03
Coef(3, 2, NC_CH2S) = -2.01191947E-06
Coef(4, 2, NC_CH2S) =  4.17906000E-10
Coef(5, 2, NC_CH2S) = -3.39716365E-14
Coef(6, 2, NC_CH2S) =  5.09259997E+04
Coef(7, 2, NC_CH2S) =  8.62650169E+00

CoefTbounds(1, NC_HCO) =    200.000
CoefTbounds(2, NC_HCO) =   1000.0
CoefTbounds(3, NC_HCO) =   3500.000

Coef(1, 1, NC_HCO) =  4.22118584E+00
Coef(2, 1, NC_HCO) = -3.24392532E-03
Coef(3, 1, NC_HCO) =  1.37799446E-05
Coef(4, 1, NC_HCO) = -1.33144093E-08
Coef(5, 1, NC_HCO) =  4.33768865E-12
Coef(6, 1, NC_HCO) =  3.83956496E+03
Coef(7, 1, NC_HCO) =  3.39437243E+00

Coef(1, 2, NC_HCO) =  2.77217438E+00
Coef(2, 2, NC_HCO) =  4.95695526E-03
Coef(3, 2, NC_HCO) = -2.48445613E-06
Coef(4, 2, NC_HCO) =  5.89161778E-10
Coef(5, 2, NC_HCO) = -5.33508711E-14
Coef(6, 2, NC_HCO) =  4.01191815E+03
Coef(7, 2, NC_HCO) =  9.79834492E+00

CoefTbounds(1, NC_CH2OH) =    200.000
CoefTbounds(2, NC_CH2OH) =  1000.0 
CoefTbounds(3, NC_CH2OH) =   3500.000

Coef(1, 1, NC_CH2OH) =  3.86388918E+00
Coef(2, 1, NC_CH2OH) =  5.59672304E-03
Coef(3, 1, NC_CH2OH) =  5.93271791E-06
Coef(4, 1, NC_CH2OH) = -1.04532012E-08
Coef(5, 1, NC_CH2OH) =  4.36967278E-12
Coef(6, 1, NC_CH2OH) = -3.19391367E+03
Coef(7, 1, NC_CH2OH) =  5.47302243E+00

Coef(1, 2, NC_CH2OH) =  3.69266569E+00
Coef(2, 2, NC_CH2OH) =  8.64576797E-03
Coef(3, 2, NC_CH2OH) = -3.75101120E-06
Coef(4, 2, NC_CH2OH) =  7.87234636E-10
Coef(5, 2, NC_CH2OH) = -6.48554201E-14
Coef(6, 2, NC_CH2OH) = -3.24250627E+03
Coef(7, 2, NC_CH2OH) =  5.81043215E+00

end subroutine init_coef

!----------------------------------------------------------------------
!Computes G/R = H/R-T*S/R for all species
subroutine my_ckgml(T, G)
implicit none

real, intent(in)  :: T
real, intent(out) :: G( 17)
integer m

do m = 1,  17
  G(m) = hml_spcs(m,T) - T*sml_spcs(m, T)
end do

return
end subroutine my_ckgml

!----------------------------------------------------------------------
!Returns H/R for a single species
real function hml_spcs(m, temp)
implicit none
integer, intent(in) :: m
real, intent(in) :: temp
integer :: nt

if (temp < coefTbounds(2,m)) then
  nt = 1
else
  nt = 2
end if

hml_spcs =      coef(6,nt,m)                     &
     + temp * ( coef(1,nt,m)                     &
     + temp * ( coef(2,nt,m) / 2.0               &
     + temp * ( coef(3,nt,m) / 3.0               &
     + temp * ( coef(4,nt,m) / 4.0               &
     + temp *   coef(5,nt,m) / 5.0 ))))

return
end function hml_spcs

!----------------------------------------------------------------------
!Returns S/R for a single species
real function sml_spcs(m, temp)
implicit none
integer, intent(in) :: m
real, intent(in) :: temp
integer :: nt

if (temp < coefTbounds(2,m)) then
  nt = 1
else
  nt = 2
end if

sml_spcs =      coef(1,nt,m)*log(temp)           &
     +          coef(7,nt,m)                     &
     + temp * ( coef(2,nt,m)                     &
     + temp * ( coef(3,nt,m) / 2.0               &
     + temp * ( coef(4,nt,m) / 3.0               &
     + temp *   coef(5,nt,m) / 4.0 )))

return
end function sml_spcs

!----------------------------------------------------------------------
subroutine gibbs_rln (T, G)

implicit none

real, intent(in) :: T
real, intent(out) :: G( 73)
real cgspl( 17)

call my_ckgml(T, cgspl)

!----------------------------------------------------------------------
!----------------------------------------------------------------------
! 1. 2O+M<=> O2+M                              
G(1) = -2.0*cgspl(NC_O)+1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 2. O+H+M<=> OH+M                             
G(2) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_O)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 3. O+H2<=> H+OH                              
G(3) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_O)-1.0*cgspl(NC_H2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 4. O+HO2<=> OH+O2                            
G(4) = -1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 5. O+CH2<=> H+HCO                            
G(5) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_CH2)-1.0*cgspl(NC_O)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 6. O+CH2S<=> H2+CO                         
G(6) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 7. O+CH3<=> H+CH2O                           
G(7) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_O)-1.0*cgspl(NC_CH3)+1.0*cgspl(NC_CH2O)

!----------------------------------------------------------------------
! 8. O+CH4<=> OH+CH3                           
G(8) = -1.0*cgspl(NC_CH4)-1.0*cgspl(NC_O)+1.0*cgspl(NC_CH3)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 9. O+CO+M<=> CO2+M                           
G(9) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)

!----------------------------------------------------------------------
! 10. O+HCO<=> OH+CO                            
G(10) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_CO)+1.0*cgspl(NC_OH)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 11. O+HCO<=> H+CO2                            
G(11) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 12. O+CH2O<=> OH+HCO                          
G(12) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_OH)-1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 13. O+CH2OH<=> OH+CH2O                        
G(13) = -1.0*cgspl(NC_O)+1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_OH)-1.0*cgspl(NC_CH2OH)

!----------------------------------------------------------------------
! 14. O2+CO<=> O+CO2                            
G(14) = +1.0*cgspl(NC_O)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 15. O2+CH2O<=> HO2+HCO                        
G(15) = +1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)-1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 16. H+O2+M<=> HO2+M                           
G(16) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 17. H+2O2<=> HO2+O2                           
G(17) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 18. H+O2+H2O<=> HO2+H2O                       
G(18) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 19. H+O2+N2<=> HO2+N2                         
G(19) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 20. H+O2<=> O+OH                              
G(20) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_O)-1.0*cgspl(NC_O2)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 21. 2H+M<=> H2+M                              
G(21) = -2.0*cgspl(NC_H)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 22. 2H+H2<=> 2H2                              
G(22) = -2.0*cgspl(NC_H)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 23. 2H+H2O<=> H2+H2O                          
G(23) = -2.0*cgspl(NC_H)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 24. 2H+CO2<=> H2+CO2                          
G(24) = -2.0*cgspl(NC_H)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 25. H+OH+M<=> H2O+M                           
G(25) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 26. H+HO2<=> O+H2O                            
G(26) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_O)-1.0*cgspl(NC_HO2)+1.0*cgspl(NC_H2O)

!----------------------------------------------------------------------
! 27. H+HO2<=> O2+H2                            
G(27) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_HO2)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 28. H+HO2<=> 2OH                              
G(28) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_HO2)+2.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 29. H+CH2+M<=> CH3+M                      
G(29) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_CH2)+1.0*cgspl(NC_CH3)

!----------------------------------------------------------------------
! 30. H+CH3+M<=> CH4+M                      
G(30) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CH4)-1.0*cgspl(NC_CH3)

!----------------------------------------------------------------------
! 31. H+CH4<=> CH3+H2                           
G(31) = -1.0*cgspl(NC_H)-1.0*cgspl(NC_CH4)+1.0*cgspl(NC_CH3)+1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 32. H+HCO+M<=> CH2O+M                     
G(32) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 33. H+HCO<=> H2+CO                            
G(33) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)+1.0*cgspl(NC_H2)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 34. H+CH2O+M<=> CH2OH+M                   
G(34) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CH2OH)-1.0*cgspl(NC_CH2O)

!----------------------------------------------------------------------
! 35. H+CH2O<=> HCO+H2                          
G(35) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_H2)-1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 36. H+CH2OH<=> H2+CH2O                        
G(36) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_H2)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_CH2OH)

!----------------------------------------------------------------------
! 37. H+CH2OH<=> OH+CH3                         
G(37) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CH3)+1.0*cgspl(NC_OH)-1.0*cgspl(NC_CH2OH)

!----------------------------------------------------------------------
! 38. H+CH2OH<=> CH2S+H2O                     
G(38) = -1.0*cgspl(NC_H)+1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_CH2OH)

!----------------------------------------------------------------------
! 39. H2+CO+M<=> CH2O+M                     
G(39) = -1.0*cgspl(NC_CO)-1.0*cgspl(NC_H2)+1.0*cgspl(NC_CH2O)

!----------------------------------------------------------------------
! 40. OH+H2<=> H+H2O                            
G(40) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_H2)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 41. 2OH<=> O+H2O                              
G(41) = +1.0*cgspl(NC_O)+1.0*cgspl(NC_H2O)-2.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 42. OH+HO2<=> O2+H2O                          
G(42) = -1.0*cgspl(NC_HO2)+1.0*cgspl(NC_O2)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 43. OH+CH2<=> H+CH2O                          
G(43) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_CH2)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 44. OH+CH2S<=> H+CH2O                       
G(44) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 45. OH+CH3<=> CH2+H2O                         
G(45) = +1.0*cgspl(NC_CH2)-1.0*cgspl(NC_CH3)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 46. OH+CH3<=> CH2S+H2O                      
G(46) = -1.0*cgspl(NC_CH3)+1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 47. OH+CH4<=> CH3+H2O                         
G(47) = -1.0*cgspl(NC_CH4)+1.0*cgspl(NC_CH3)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 48. OH+CO<=> H+CO2                            
G(48) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 49. OH+HCO<=> H2O+CO                          
G(49) = +1.0*cgspl(NC_CO)+1.0*cgspl(NC_H2O)-1.0*cgspl(NC_OH)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 50. OH+CH2O<=> HCO+H2O                        
G(50) = +1.0*cgspl(NC_H2O)-1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_OH)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 51. OH+CH2OH<=> H2O+CH2O                      
G(51) = +1.0*cgspl(NC_H2O)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_CH2OH)-1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 52. HO2+CH2<=> OH+CH2O                        
G(52) = -1.0*cgspl(NC_CH2)-1.0*cgspl(NC_HO2)+1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 53. HO2+CH3<=> O2+CH4                         
G(53) = +1.0*cgspl(NC_CH4)-1.0*cgspl(NC_HO2)-1.0*cgspl(NC_CH3)+1.0*cgspl(NC_O2)

!----------------------------------------------------------------------
! 54. HO2+CO<=> OH+CO2                          
G(54) = -1.0*cgspl(NC_HO2)+1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CO)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 55. CH2+O2<=> OH+HCO                          
G(55) = -1.0*cgspl(NC_CH2)-1.0*cgspl(NC_O2)+1.0*cgspl(NC_OH)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 56. CH2+H2<=> H+CH3                           
G(56) = +1.0*cgspl(NC_H)-1.0*cgspl(NC_CH2)+1.0*cgspl(NC_CH3)-1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 57. CH2+CH4<=> 2CH3                           
G(57) = -1.0*cgspl(NC_CH4)-1.0*cgspl(NC_CH2)+2.0*cgspl(NC_CH3)

!----------------------------------------------------------------------
! 58. CH2S+N2<=> CH2+N2                       
G(58) = +1.0*cgspl(NC_CH2)-1.0*cgspl(NC_CH2S)

!----------------------------------------------------------------------
! 59. CH2S+O2<=> H+OH+CO                      
G(59) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)-1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 60. CH2S+O2<=> CO+H2O                       
G(60) = +1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)-1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_H2O)

!----------------------------------------------------------------------
! 61. CH2S+H2<=> CH3+H                        
G(61) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CH3)-1.0*cgspl(NC_CH2S)-1.0*cgspl(NC_H2)

!----------------------------------------------------------------------
! 62. CH2S+H2O<=> CH2+H2O                     
G(62) = +1.0*cgspl(NC_CH2)-1.0*cgspl(NC_CH2S)

!----------------------------------------------------------------------
! 63. CH2S+CH4<=> 2CH3                        
G(63) = -1.0*cgspl(NC_CH4)+2.0*cgspl(NC_CH3)-1.0*cgspl(NC_CH2S)

!----------------------------------------------------------------------
! 64. CH2S+CO<=> CH2+CO                       
G(64) = +1.0*cgspl(NC_CH2)-1.0*cgspl(NC_CH2S)

!----------------------------------------------------------------------
! 65. CH2S+CO2<=> CH2+CO2                     
G(65) = +1.0*cgspl(NC_CH2)-1.0*cgspl(NC_CH2S)

!----------------------------------------------------------------------
! 66. CH2S+CO2<=> CO+CH2O                     
G(66) = +1.0*cgspl(NC_CO)-1.0*cgspl(NC_CO2)-1.0*cgspl(NC_CH2S)+1.0*cgspl(NC_CH2O)

!----------------------------------------------------------------------
! 67. CH3+O2<=> OH+CH2O                         
G(67) = -1.0*cgspl(NC_CH3)-1.0*cgspl(NC_O2)+1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_OH)

!----------------------------------------------------------------------
! 68. CH3+HCO<=> CH4+CO                         
G(68) = +1.0*cgspl(NC_CH4)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_CH3)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 69. CH3+CH2O<=> HCO+CH4                       
G(69) = +1.0*cgspl(NC_CH4)-1.0*cgspl(NC_CH3)-1.0*cgspl(NC_CH2O)+1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 70. HCO+H2O<=> H+CO+H2O                       
G(70) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 71. HCO+M<=> H+CO+M                           
G(71) = +1.0*cgspl(NC_H)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 72. HCO+O2<=> HO2+CO                          
G(72) = +1.0*cgspl(NC_HO2)+1.0*cgspl(NC_CO)-1.0*cgspl(NC_O2)-1.0*cgspl(NC_HCO)

!----------------------------------------------------------------------
! 73. CH2OH+O2<=> HO2+CH2O                      
G(73) = +1.0*cgspl(NC_HO2)-1.0*cgspl(NC_O2)+1.0*cgspl(NC_CH2O)-1.0*cgspl(NC_CH2OH)

G(:) = G(:)/T
return
end subroutine gibbs_rln

!----------------------------------------------------------------------
! Computes the gibbs_energy lookup index given temperature
! This can be done once, stored and reused for all reactions.
! Note that T is in non-dimensional units.
!----------------------------------------------------------------------
subroutine gibbs_compute_index(T)
use param_m, only: nx, ny, nz
implicit none

real, dimension(nx, ny, nz), intent(in) :: T
integer i, j, k

do k = 1, nz
  do j = 1, ny
    do i = 1, nx
      index(i, j, k) = int( (T(i,j,k)-nd_temp_lobound)*nd_inv_inc ) + 1
    end do
  end do
end do

return
end subroutine gibbs_compute_index


!----------------------------------------------------------------------
!Returns the change in gibbs energy for a given reaction number
!at all points in the domain.
! Note that T is in non-dimensional units.
!----------------------------------------------------------------------
subroutine gibbs_lookup_all(T, r, G)
use param_m, only: nx, ny, nz
implicit none

integer, intent(in) :: r
real, dimension(nx, ny, nz), intent(in) :: T
real, dimension(nx, ny, nz), intent(out) :: G
integer i, j, k, n

do k = 1, nz
  do j = 1, ny
    do i = 1, nx
!      n = index(i,j,k)
      n = int( (T(i,j,k)-nd_temp_lobound)*nd_inv_inc ) + 1
      G(i,j,k) = Gibbs_table_aa(n,r)*T(i,j,k) + Gibbs_table_bb(n,r)
    end do
  end do
end do

return
end subroutine gibbs_lookup_all
!----------------------------------------------------------------------

!----------------------------------------------------------------------
!Returns the change in gibbs energy for a given reaction number
!Note that T is in non-dimensional units.
subroutine gibbs_lookup(T, r, G)
implicit none
real, intent(in) :: T
integer, intent(in) :: r
real, intent(out) :: G

integer n

n = int( (T-nd_temp_lobound)*nd_inv_inc ) + 1
G = Gibbs_table_aa(n,r)*T + Gibbs_table_bb(n,r)

end subroutine gibbs_lookup
!----------------------------------------------------------------------

!----------------------------------------------------------------------
end module gibbs_rxn_table_m
