language: c
compiler:
    - gcc
    - clang
os:
    - precise
before_install:
    - sudo apt-get update
    - sudo apt-get install mpich python3-numpy python3-mpi4py swig
script:
    - ./autogen.sh
    - ./configure CC=mpicc FC=mpif90 --enable-python-bindings
    - make
    - sudo make install
