language: c
os: linux
jobs:
  include:
  - name: "cmake"
    compiler:
      - gcc
      - clang
    env: BUILD_SYS=cmake
  - name: "autotools"
    compiler:
      - gcc
      - clang
    env: BUILD_SYS=autotools
before_install:
    - sudo apt-get update
    - sudo apt-get install mpich libmpich-dev
script: scripts/ci/build.sh $BUILD_SYS
