/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Fixed Gemini cookie */
/* #undef GNI_COOKIE */

/* Fixed Gemini ptag */
/* #undef GNI_PTAG */

/* Define if you have CRAY_PMI. */
/* #undef HAVE_CRAY_PMI */

/* Define if you have Cray Portals. */
/* #undef HAVE_CRAY_PORTALS */

/* Define if you have CRAY_UGNI. */
/* #undef HAVE_CRAY_UGNI */

/* Define if you have the DCMF. */
#define HAVE_DCMF 1

/* Define to 1 if you have the <dcmf.h> header file. */
#define HAVE_DCMF_H 1

/* Define to 1 if you have <infiniband/verbs.h>. */
/* #undef HAVE_IBVERBS_H */

/* Define if you have the Infiniband. */
/* #undef HAVE_INFINIBAND */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <p3nal_utcp.h> header file. */
/* #undef HAVE_P3NAL_UTCP_H */

/* Define to 1 if you have the <p3rt/p3rt.h> header file. */
/* #undef HAVE_P3RT_P3RT_H */

/* Define if you have the Portals. */
/* #undef HAVE_PORTALS */

/* Define to 1 if you have <portals3.h>. */
/* #undef HAVE_PORTALS3_H */

/* Define to 1 if you have <portals/portals3.h>. */
/* #undef HAVE_PORTALS_PORTALS3_H */

/* Define if you have POSIX threads libraries and header files. */
#define HAVE_PTHREAD 1

/* Define to 1 if you have the `PtlACEntry' function. */
/* #undef HAVE_PTLACENTRY */

/* Define to 1 if you have the `PtlErrorStr' function. */
/* #undef HAVE_PTLERRORSTR */

/* Define to 1 if you have the `PtlEventKindStr' function. */
/* #undef HAVE_PTLEVENTKINDSTR */

/* Define to 1 if you have the `PtlGetJid' function. */
/* #undef HAVE_PTLGETJID */

/* Define to 1 if you have the `PtlNIFailStr' function. */
/* #undef HAVE_PTLNIFAILSTR */

/* Define to 1 if the system has the type `ptl_eq_handler_t'. */
/* #undef HAVE_PTL_EQ_HANDLER_T */

/* Define if you have PTL_NOACK_REQ. */
/* #undef HAVE_PTL_NOACK_REQ */

/* Define if you have PTL_NO_ACK_REQ. */
/* #undef HAVE_PTL_NO_ACK_REQ */

/* Define to 1 if the system has the type `ptl_time_t'. */
/* #undef HAVE_PTL_TIME_T */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "dataspaces-codemerge-template"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "dataspaces-codemerge-template"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "dataspaces-codemerge-template 1.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "dataspaces-codemerge-template"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.0"

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.2.0"
