#!/usr/bin/perl
#RG Sept 2008: Input script to auto-generate input files from template for different grid density / topologies
#as listed in "inputfiles"


$input_file = "inputfiles";
open( INPFILE, $input_file ) || die( "Could not open list of input files to make, $input_file" );

while( $infile = <INPFILE> ){
	if( $infile =~ /^\#/ ){
		next;
	}

	@params = split( /,/, $infile );
        $npx = $params[0];
        $npy = $params[1];
        $npz = $params[2];
        $nx = $params[3];
        $ny = $params[4];
        $nz = $params[5];
        $nproc = $npx*$npy*$npz;
        $ngrid = $nx*$ny*$nz;
        $ext = $ngrid."_".$nproc;
	
	$template_file = "s3d.in.template";
	open(TEMPLATE, $template_file) || die("Could not open input template $template_file" );

	$outfile = "s3d.in.$ext";


	open(OUTFILE, ">", $outfile ) || die("Could not open file: $outfile");

	print " Writing input file: ", $outfile, "\n";

	while($line = <TEMPLATE> ) {
		if( $line =~ /nx_g/ ) {
			$line =~ s/(^\d)/$nx*$npx/e;
			print OUTFILE $line;
			next;
		}
		if( $line =~ /ny_g/ ) {
			$line =~ s/(^\d)/$ny*$npy/e;
			print OUTFILE $line;
			next;
		}
		if( $line =~ /nz_g/ ) {
			$line =~ s/(^\d)/$nz*$npz/e;
			print OUTFILE $line;
			next;
		}
		if( $line =~ /npx/ ) {
			$line =~ s/(^\d)/$npx/e;
			print OUTFILE $line;
			next;
		}
		if( $line =~ /npy/ ) {
			$line =~ s/(^\d)/$npy/e;
			print OUTFILE $line;
			next;
		}
		if( $line =~ /npz/ ) {
			$line =~ s/(^\d)/$npz/e;
			print OUTFILE $line;
			next;
		}

		print OUTFILE $line;
		next;
	}

	close(TEMPLATE);
 	close(OUTFILE);

  do "rankgen.pl" || die "Could not generated rank reorder: $!";
}
