#!/bin/bash
#PBS -N test_dspaces
#PBS -A XXXX 
#PBS -j oe
#PBS -q debug
#PBS -l walltime=00:50:00,size=72

cd $PBS_O_WORKDIR

rm -f conf

aprun -n 4 ./dataspaces_server -s 4 -c 48 &

## Give some time for the servers to load and startup
while [ ! -f conf ]; do
    sleep 2s
done

aprun -n 16 ./test_writer DATASPACES 16 4 4 1 32 32 128 10 1 3 &

sleep 5

aprun -n 32 ./test_reader DATASPACES 32 4 4 2 32 32 64 10 2 3 &

wait
