#!/bin/sh
#PBS -N block_test
#PBS -A CHM043DNS
#PBS -q debug
#PBS -j oe
#PBS -m abe
#PBS -M jcbenne@sandia.gov,janine.bennett@gmail.com
#PBS -l walltime=1:00:00
#PBS -l gres=widow2
#PBS -l size=16

cd $PBS_O_WORKDIR

#aprun -n 1 ./serialTest /lustre/widow2/scratch/jcbenne/git_dnscollab/topology/StreamingTopology/trunk/data/blob_50_50_50.raw  50 50 50 2 1 1 1 > serialTest.out

aprun -n 1 ./serialTest /lustre/widow2/scratch/jcbenne/git_dnscollab/topology/StreamingTopology/trunk/data/blob_50_50_50.raw  50 50 50 2 1 1 1 > serialTest.out
