if(DSPACES_FABRIC STREQUAL "INFINIBAND")
    #find_package(Verbs REQUIRED)
    if(Verbs_FOUND)
        set(HAVE_VERBS 1)
    endif()
elseif(DSPACES_FABRIC STREQUAL "GNI")
    find_package(GNI REQUIRED)
    if(GNI_FOUND)
        set(HAVE_UGNI 1)
    endif()
elseif(DSPACES_FABRIC STREQUAL "TCP")
    set(HAVE_TCP_SOCKET 1)
else()
    find_package(GNI)
    if(GNI_FOUND)
        set(HAVE_UGNI 1)
        set(DSPACES_FABRIC "GNI")
    else()
#        find_package(Verbs)
        if(Verbs_FOUND)
            set(HAVE_VERBS 1)
            set(DSPACE_FABRIC "INFINIBAND")
        else()
            set(HAVE_TCP_SOCKETS 1)
            set(DSPACES_FABRIC "TCP")
        endif()
    endif()
endif()
